web/urls.py
from django.urls import path, include
from web.views import index, subscribe, contact, product


app_name = "web"

urlpatterns = [
    path("", index, name = "index"),
    path("subscribe/", subscribe, name="subscribe"),
    path("contact/", contact, name="contact"),
    path("product/<int:pk>/", product, name="product")
]

wibbitz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("web.urls", namespace = "web")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

web/models.py
from django.db import models


CONTENT_TYPE = (
    ("blog_post", "Blog Post"),
    ("webinar", "Webinar"),
    ("report", "Report")
)

COMPANY_SIZE = (
    ("1", "1-10"),
    ("2", "11-50"),
    ("3", "51-200"),
    ("4", "201-500")
)

INDUSTRY = (
    ("1", "Agriculture"),
    ("2", "Banking & Finance"),
    ("1", "Business Services & Software")
)

JOB_ROLE = (
    ("1", "C-Suite"),
    ("2", "VP")
)

COUNTRY = (
    ("us", "United States"),
    ("albania", "Albania")
)
class Subscribe(models.Model):
    email = models.EmailField()
    
    def __str__(self):
        return self.email


class Customer(models.Model):
    product = models.ForeignKey("web.Product", on_delete=models.CASCADE)
    logo = models.FileField(upload_to = "customers/")
    white_logo = models.FileField(upload_to="customers/", blank=True, null=True)

    class Meta:
        ordering = ["id"]


class Feature(models.Model):
    image = models.ImageField(upload_to = "features/")
    icon = models.FileField(upload_to = "features/")
    icon_background = models.CharField(max_length = 128 )
    title = models.CharField(max_length = 128)
    description = models.TextField()
    testimonial_description = models.TextField()
    testimonial_author = models.CharField(max_length = 128)
    author_designation = models.CharField(max_length = 128)
    testimonial_logo = models.FileField()

    def __str__(self):
        return self.title


class VideoBlog(models.Model):
    image = models.ImageField(upload_to = "VideoBlog/image/")
    title = models.CharField(max_length = 128)
    logo = models.FileField(upload_to = "VideoBlog/logo/")

    def __str__(self):
        return self.title


class Testimonial(models.Model):
    image = models.ImageField(upload_to="testimonial/image")
    logo = models.FileField(upload_to="testimonial/logo", null = True, blank = True)
    description = models.CharField(max_length=252)
    name = models.CharField(max_length=128) 
    designation = models.CharField(max_length=128) 
    company_name = models.CharField(max_length=128) 
    is_featured = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class MarketingFeature(models.Model):
    image = models.FileField(upload_to="marketing/")
    title = models.CharField(max_length=128)
    description = models.CharField(max_length=128)

    def __str__(self):
        return self.title


class Product(models.Model):
    image = models.ImageField(upload_to="product/image/")
    hero_image = models.ImageField(upload_to="product/image/")
    name = models.CharField(max_length=148)
    title = models.CharField(max_length=148)
    description = models.TextField()
    background_color = models.CharField(max_length=148)
    logo = models.FileField(upload_to="product/logo/")

    def __str__(self):
        return self.name


class Blog(models.Model):
    image = models.ImageField(upload_to="blog/")
    title = models.CharField(max_length=128)
    content_type = models.CharField(max_length=128, choices=CONTENT_TYPE)

    def __str__(self):
        return self.content_type


class Contact(models.Model):
    email = models.EmailField()
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    company = models.CharField(max_length=128)
    company_size = models.CharField(max_length=128, choices=COMPANY_SIZE)
    industry = models.CharField(max_length=128, choices=INDUSTRY)
    job_role = models.CharField(max_length=128, choices=JOB_ROLE)
    country = models.CharField(max_length=128, choices=COUNTRY)
    user_agreement = models.BooleanField(default=False)

    class Meta:
        db_table = "web_contact"
        ordering = ["-id"]

    def __str__(self):
        return self.email

web/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.widgets import EmailInput, TextInput, Select
from web.models import Contact
from web.models import COMPANY_SIZE, INDUSTRY, JOB_ROLE,COUNTRY


EMPTY_COMPANY_SIZE = (("", "Company Size"),) + COMPANY_SIZE
EMPTY_INDUSTRY = (("", "Industry"),) + INDUSTRY
EMPTY_JOB_ROLE = (("", "Job Role"),) + JOB_ROLE
EMPTY_COUNTRY = (("", "Country"),) + COUNTRY
class ContactForm(ModelForm):
    company_size = forms.ChoiceField(choices=EMPTY_COMPANY_SIZE)
    industry = forms.ChoiceField(choices=EMPTY_INDUSTRY)
    job_role = forms.ChoiceField(choices=EMPTY_JOB_ROLE)
    country = forms.ChoiceField(choices=EMPTY_COUNTRY)
    class Meta:
        model = Contact
        fields = "__all__"
        widgets = {
            "email": EmailInput(attrs={"placeholder":"Work Email"}),
            "first_name": TextInput(attrs={"placeholder":"First Name"}),
            "last_name": TextInput(attrs={"placeholder":"Last Name"}),
            "company": TextInput(attrs={"placeholder":"Company"})
        }

web/views.py
import json
from django.shortcuts import render, get_object_or_404
from django.http.response import HttpResponse
from web.models import Subscribe, Customer, Feature, VideoBlog, Testimonial, MarketingFeature, Product, Blog
from web.forms import ContactForm


def index(request):
    customer = Customer.objects.all()
    latest_customer = Customer.objects.all()[:4]
    feature = Feature.objects.all()
    videoblog = VideoBlog.objects.all()
    featured_testimonial = Testimonial.objects.filter(is_featured=True)
    non_featured_testimonial = Testimonial.objects.filter(is_featured=False)
    marketing = MarketingFeature.objects.all()
    product = Product.objects.all()
    blog = Blog.objects.all()

    form = ContactForm()

    context = {
        "customers" : customer,
        "latest_customers" : latest_customer,
        "features" : feature,
        "videoblogs" : videoblog,
        "featured_testimonials" : featured_testimonial,
        "non_featured_testimonials" : non_featured_testimonial,
        "marketings" : marketing,
        "products" : product,
        "blogs" : blog,
        "form" : form

    }
    return render(request, "index.html", context = context)
    
def subscribe(request):
    email = request.POST.get("email")
    if not Subscribe.objects.filter(email = email).exists():
        Subscribe.objects.create(
            email = email
        )
        response_data = {
            "status" : "success",
            "title" : "subscription was successfull",
            "message" : "Email registration was succesfull"
        }
    else:
        response_data = {
            "status" : "error",
            "title" : "subscription has failed",
            "message" : "Email registration was NOT succesfull"
        }
    return HttpResponse(json.dumps(response_data), content_type = "application/javascript")


def contact(request):
    form = ContactForm(request.POST)
    if form.is_valid():
        form.save()

        response_data = {
        "status" : "success",
        "title" : "subscription was successfull",
        "message" : "Email registration was succesfull"
    }
    else:
        response_data = {
            "status" : "error",
            "title" : "subscription has failed",
            "message" : "Email registration was NOT succesfull"
        }
    return HttpResponse(json.dumps(response_data), content_type = "application/javascript")
    

def product(request,pk):
    product = get_object_or_404(Product.objects.filter(pk=pk))
    customers = Customer.objects.filter(product=product)
    context = {
        "product":product,
        "customers":customers
    }
    return render(request,"product.html",context=context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <title>Wibbitz: Online video creation made easy</title>
    <link
      rel="stylesheet"
      href="{% static 'css/style.css' %}"
      type="text/css" />
    <link
      rel="stylesheet"
      href="{% static 'css/fontello.css' %}"
      type="text/css" />

    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="{% static 'images/favicon.png' %}" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta property="og:image" content="" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
  </head>
  <body>
    <header>
      <h1 class="left">
        <a href="#"><img src="{% static 'images/logo.svg' %}" alt="Logo" /></a>
      </h1>
      <nav class="middle">
        <ul>
          <li><a href="#">Solutions</a></li>
          <li><a href="#">Enterprise</a></li>
          <li><a href="#">Use Cases</a></li>
          <li><a href="#">Pricing</a></li>
          <li><a href="#">Resources</a></li>
          <li><a href="#">Company</a></li>
        </ul>
      </nav>
      <nav class="right">
        <ul>
          <li><a href="#">Login</a></li>
          <li><a href="#" class="button">Get a Demo</a></li>
        </ul>
      </nav>
    </header>
    {% block content %} {% endblock %}
    <footer>
      <section class="wrapper">
        <section class="top">
          <div class="item large">
            <h2>
              The online video editor trusted by teams to make professional
              video in minutes.
            </h2>
            <div class="social">
              <ul>
                <li>
                  <a href=""
                    ><img src="{% static 'images/facebook-blue.svg' %}" alt=""
                  /></a>
                </li>
                <li>
                  <a href=""
                    ><img src="{% static 'images/twitter-blue.svg' %}" alt=""
                  /></a>
                </li>
                <li>
                  <a href=""
                    ><img src="{% static 'images/linkedin-blue.svg' %}" alt=""
                  /></a>
                </li>
                <li>
                  <a href=""
                    ><img src="{% static 'images/youtube-blue.svg' %}" alt=""
                  /></a>
                </li>
                <li>
                  <a href=""
                    ><img src="{% static 'images/instagram.svg' %}" alt=""
                  /></a>
                </li>
              </ul>
            </div>
          </div>
          <div class="item">
            <h5>Solutions</h5>
            <ul>
              {% for product in products %}
              <li>
                <a href="#">
                  <img src="{{product.logo.url}}" alt="" />
                  <span>{{product.name}}</span>
                </a>
              </li>
              {% endfor %}
            </ul>
          </div>
          <div class="item">
            <h5>Use Cases</h5>
            <ul>
              <li><a href="#">Marketing</a></li>
              <li><a href="#">Social Media</a></li>
              <li><a href="#">Publishers</a></li>
              <li><a href="#">Agencies</a></li>
              <li><a href="#">Corporate Communications</a></li>
              <li><a href="#">Enterprise</a></li>
            </ul>
          </div>
          <div class="item">
            <h5>Resources</h5>
            <ul>
              <li><a href="#">Learning Center</a></li>
              <li><a href="#">Customers</a></li>
              <li><a href="#">Video Showcase</a></li>
            </ul>
            <a href="#" class="bold">Pricing</a>
          </div>
          <div class="item">
            <h5>Company</h5>
            <ul>
              <li><a href="#">About Us</a></li>
              <li><a href="#">Jobs</a></li>
              <li><a href="#">Press</a></li>
            </ul>
            <h5>Legal</h5>
            <ul>
              <li><a href="#">Terms and Conditions</a></li>
              <li><a href="#">Privacy Policy</a></li>
            </ul>
          </div>
        </section>
        <section class="bottom">
          <div class="title">
            <img src="{% static 'images/globe-gray.svg' %}" alt="" />
            <span>Choose language</span>
          </div>
          <div class="bottom">
            <ul>
              <li><a href="#">English</a></li>
              <li><a href="#">Français</a></li>
            </ul>
          </div>
        </section>
      </section>
    </footer>

    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/sweetalert2.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

templates/index.html
{% extends "base.html" %} {% load static %} {% block content %}
<section id="spotlight">
  <section class="wrapper flex-wrapper">
    <section class="content">
      <h1>The quickest and easiest online video editor for every team</h1>
      <p>
        Wibbitz gives you the freedom to create short form video online in
        minutes – no experience necessary.
      </p>
      <form action="{% url 'web:subscribe' %}" method="post" class="ajax">
        {% csrf_token %}
        <input type="email" name="email" placeholder="Enter your work email" />
        <button type="submit">Get a Demo</button>
      </form>
    </section>
    <div class="right_container">
      <div class="img_container">
        <img src="{% static 'images/home-hero.svg' %}" alt="" />
      </div>
      <a href="#" class="play-button">
        <img src="{% static 'images/play.svg' %}" alt="" />
      </a>
    </div>
  </section>
</section>
<section id="brands">
  <section class="wrapper">
    <p>Trusted by content creators across the world</p>
    <ul>
      {% for customer in customers %}
      <li>
        <a href="#"><img src="{{ customer.logo.url }}" alt="" /></a>
      </li>
      {% endfor %}
    </ul>
  </section>
</section>
<section id="fearures">
  {% for feature in features %}
  <section class="feature">
    <section class="wrapper flex-wrapper">
      <div class="img_container">
        <img src="{{ feature.image.url }}" alt="" />
      </div>
      <div class="content">
        <div
          class="icon"
          style="background-color: {{ feature.icon_background }};">
          <img src="{{ feature.icon.url }}" alt="" />
        </div>
        <h3>{{ feature.title }}</h3>
        <p>{{ feature.description }}</p>
        <a href="#" class="button">Get a Demo</a>
        <div class="review">
          <hr class="dash" />
          <blockquote>"{{ feature.testimonial_description }}"</blockquote>
          <span>
            <small>{{ feature.testimonial_author }}, </small>
            {{ feature.author_designation }}
          </span>
          <img src="{{ feature.testimonial_logo.url }}" alt="" />
        </div>
      </div>
    </section>
  </section>
  {% endfor %}
</section>
<section id="reviews">
  <section class="wrapper">
    <section class="top">
      <h3>Create video like these leading brands</h3>
    </section>
    <section class="bottom">
      <ul>
        {% for videoblog in videoblogs %}
        <li>
          <div
            class="top"
            style="
              background-image: url({{videoblog.image.url}});
            ">
            <span class="play">
              <img src="{% static 'images/play.svg' %}" alt="" />
            </span>
            <div class="logo">
              <img src="{{ videoblog.logo.url }}" alt="" />
            </div>
          </div>
          <h4>{{ videoblog.title }}</h4>
        </li>
        {% endfor %}
      </ul>
    </section>
  </section>
</section>
<section id="testimonials">
  <section class="wrapper">
    <ul>
      {% for testimonial in featured_testimonials %}
      <li>
        <div class="top">
          <img src="{{ testimonial.image.url }}" alt="" class="cover" />
          <div class="logo">
            <img src="{{ testimonial.logo.url }}" alt="" />
          </div>
        </div>
        <div class="bottom">
          <blockquote>{{ testimonial.description }}</blockquote>
          <h6>{{ testimonial.name }}</h6>
          <span>{{ testimonial.designation }}</span>
          <small>{{ testimonial.company_name }}</small>
        </div>
      </li>
      {% endfor %}
    </ul>
  </section>
</section>
<section id="features">
  <section class="wrapper">
    <section class="top">
      <h3>Wibbitz gives every team the freedom to create</h3>
    </section>
    <section class="content">
      <ul>
        {% for marketing in marketings %}
        <li>
          <div class="content">
            <a href="#" class="img_container"
              ><img src="{{ marketing.image.url }}" alt=""
            /></a>
            <h3><a href="#">{{ marketing.title }}</a></h3>
            <p>{{ marketing.description }}</p>
            <a href="#" class="button">Learn More</a>
          </div>
        </li>
        {% endfor %}
      </ul>
    </section>
    <section class="bottom">
      <span class="icon"
        ><img src="{% static 'images/star.svg' %}" alt=""
      /></span>
      <div class="element">
        <p>
          Empower your whole team to create an engaging video in 7 minutes or
          less.
        </p>
        <a href="#" class="button">Get a Demo</a>
      </div>
    </section>
  </section>
</section>
<section id="products">
  <section class="wrapper">
    <section class="top">
      <h3>Our three video solutions are built for every type of business</h3>
    </section>
    <ul>
      {% for product in products %}
      <li class="one">
        <div class="logo">
          <img src="{{ product.logo.url }}" alt="" />
        </div>
        <h1>{{ product.name }}</h1>
        <p>{{ product.description }}</p>
        <a href="{% url 'web:product' pk=product.pk %}" class="button"
          >Learn More</a
        >
        <div class="img_bottom">
          <img src="{{ product.image.url }}" alt="" class="hero" />
        </div>
      </li>
      {% endfor %}
    </ul>
  </section>
</section>
<section id="blog">
  <section class="wrapper">
    <section class="top">
      <h3>
        Video resources: Insider advice on how to bring your content to life
      </h3>
    </section>
    <ul>
      {% for blog in blogs %}
      <li>
        <img src="{{ blog.image.url}}" alt="" />
        <span style="color: #0055fb" class="label">
          {{ blog.content_type }}
        </span>
        <h2>{{ blog.title }}</h2>
        <a href="#" class="button">Read blog</a>
      </li>
      {% endfor %}
    </ul>
    <div class="bottom">
      <a href="#" class="button">Explore All Resources</a>
    </div>
  </section>
</section>
<section id="contact">
  <section class="wrapper">
    <div class="left">
      <h3>Ready to get started?</h3>
      <p>
        Schedule a demo of our online video editor to start making your own
        short form videos today. We’ll help you elevate your video content
        strategy.
      </p>

      <hr class="line" />

      <div class="testimonials">
        <h5>Why do content creators choose Wibbitz?</h5>
        <div class="content">
          <blockquote>
            "Wibbitz strengthens the communications strategy at our company by
            allowing us to produce more videos, faster, while maintaining top
            level of quality."
          </blockquote>
          <h6>Jeff Cucinell</h6>
          <span class="role"> Director of Social Strategy, iHeartRadio</span>
        </div>
        <ul class="people">
          <li class="active">
            <img src="{% static 'images/profile1.jpg' %}" alt="" />
          </li>
          <li><img src="{% static 'images/profile2.jpg' %}" alt="" /></li>
          <li><img src="{% static 'images/profile3.jpg' %}" alt="" /></li>
          <li><img src="{% static 'images/profile4.jpg' %}" alt="" /></li>
        </ul>
      </div>
      <hr class="line bottom" />
      <div class="companies">
        <ul>
          {% for customer in latest_customers %}
          <li>
            <img src="{{customer.white_logo.url}}" alt="" />
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
    <div class="right">
      <div class="content">
        <h4>Help us get to know you.</h4>
        <form action="{% url 'web:contact' %}" method="post" class="ajax">
          {% csrf_token %}
          <div class="one_by_two">{{form.email}}</div>
          <div class="one_by_two">{{form.first_name}}</div>
          <div class="one_by_two">{{form.last_name}}</div>
          <div class="one_by_two">{{form.company}}</div>
          <div class="one_by_two">{{form.company_size}}</div>
          <div class="one_by_two">{{form.industry}}</div>
          <div class="one_by_two">{{form.job_role}}</div>
          <div class="one_by_two">{{form.country}}</div>
          <div class="full checkbox">
            {{form.user_agreement}}
            <label for="{{form.user_agreement.id_for_label}}"
              >Yes, I'd like to receive occasional marketing emails from
              Wibbitz. I have the right to opt out at any time.
              <a href="#">View privacy policy.</a>
            </label>
          </div>
          <div class="full">
            <input class="submit" type="submit" value="Get a Demo" />
          </div>
        </form>
      </div>
    </div>
  </section>
</section>
{% endblock %}

templates/product.html
{% extends "base.html" %} {% load static %} {% block content %}

<section id="product" style="background-color: {{product.background_color}};">
  <section class="wrapper">
    <a href="#" class="logo-badge">
      <img src="{{product.logo.url}}" alt="" />
      {{product.name}}
    </a>
    <h1>{{product.title}}</h1>
    <p>{{product.description}}</p>
    <a href="#" class="button">Get in Touch</a>
    <img src="{{product.hero_image.url}}" alt="Hero Image" class="hero" />
  </section>
</section>
<section id="inner-page-brands">
  <section class="wrapper">
    {% if customers %}
    <h6>Leading brands trust Wibbitz for video</h6>
    <ul>
      {% for customer in customers %}
      <li>
        <a href="#">
          <img src="{{customer.logo.url}}" alt="" />
        </a>
      </li>
      {% endfor %}
    </ul>
    {% endif %}
  </section>
</section>
{% endblock %}